### ISSUE TITLE
glosbevore_animated_film_soLG submission

### ISSUE THREAD

**Issue by animationista** [libregraphicsmeeting/state-of-lg-2019#14]
Hey,
here's the material for my short film glosbevore for the state of LG.

Regards,
David Rylander,
Sweden
![glosbevore-0](https://user-images.githubusercontent.com/1432719/58220005-596eef00-7d0d-11e9-9974-9dc557299ecd.png)
![glosbevore-1](https://user-images.githubusercontent.com/1432719/58220006-596eef00-7d0d-11e9-8596-025f5fd3fc01.png)
[glosbevore.txt](https://github.com/libregraphicsmeeting/state-of-lg-2019/files/3209977/glosbevore.txt)
Also please note the video link in text file.

**Comment by aoloe** [comment]
thanks! i've added the slides and movie to the repository.
