### ISSUE TITLE
Filmulator and librtprocess (shared)

### ISSUE THREAD

**Issue by CarVac** [libregraphicsmeeting/state-of-lg-2019#15]
Here are my slides and notes for the presentation.
![Filmulator-1](https://user-images.githubusercontent.com/4342361/58226026-c6c15680-7cf2-11e9-9ca5-a6dd06382024.png)
![Filmulator-2](https://user-images.githubusercontent.com/4342361/58226029-ca54dd80-7cf2-11e9-8068-abaa199fb6da.png)
![Filmulator-3](https://user-images.githubusercontent.com/4342361/58226031-cde86480-7cf2-11e9-8295-444215dec373.png)

[Filmulator.txt](https://github.com/libregraphicsmeeting/state-of-lg-2019/files/3210267/Filmulator.txt)

**Comment by aoloe** [comment]
thanks, i've added the slides to the repository!
