### ISSUE TITLE
FontForge Slides

### ISSUE THREAD

**Issue by frank-trampe** [libregraphicsmeeting/state-of-lg-2019#30]

**Comment by frank-trampe** [comment]
Here is the formatted package.

[fontforge.txt](https://github.com/libregraphicsmeeting/state-of-lg-2019/files/3227595/fontforge.txt)
![fontforge-0](https://user-images.githubusercontent.com/2512464/58477970-8579de00-811a-11e9-9cb1-341cbb7429b4.png)
![fontforge-1](https://user-images.githubusercontent.com/2512464/58477973-86127480-811a-11e9-90f3-f73d41b12c99.png)

**Comment by frank-trampe** [comment]
And here is a PDF for future reference.

[Slides_1_2.pdf](https://github.com/libregraphicsmeeting/state-of-lg-2019/files/3227602/Slides_1_2.pdf)

**Comment by frank-trampe** [comment]
Sorry for the delay; my Internet connectivity in transit has not been as good as I had expected.

**Comment by aoloe** [comment]
thanks
