### ISSUE TITLE
Exiv2 Presentation

### ISSUE THREAD

**Issue by clanmills** [libregraphicsmeeting/state-of-lg-2019#4]
Thank you for the invitation to be part of your presentation.  I attach slides and speaker notes.  Please let me know if you need changes or clarification.

[LGM-Exiv2.zip](https://github.com/libregraphicsmeeting/state-of-lg-2019/files/3124937/LGM-Exiv2.zip)

**Comment by aoloe** [comment]
thanks, i've added the file 09d687078
